config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :short_urls
  get '/search', to: 'short_urls#redirect'
  get '/visit_histories', to: 'short_urls#check_visit_histories'

  root 'short_urls#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/short_url.rb
class ShortUrl < ApplicationRecord

    before_create :generate_short_url

    validates :full_url, presence: true, uniqueness: true
    validates :code, uniqueness: true

    has_many :visit_histories, dependent: :destroy

    def generate_short_url
      self.code ||= SecureRandom.hex(4)
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: %i[ user admin ]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end
end

app/models/visit_history.rb
class VisitHistory < ApplicationRecord
  belongs_to :short_url, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController

    before_action :authenticate_admin!, except: %i[ index redirect show ]
    before_action :find_short_url, only: %i[ show edit update destroy ]

  def index
    @short_urls = ShortUrl.all
  end

  def new
    @short_url = ShortUrl.new
  end

  def create
    @short_url = ShortUrl.new(short_url_params)

    if @short_url.save
      redirect_to root_path, notice: 'Short URL was successfully created!'
    else
      render :new, alert: 'Please try again'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @short_url.update(short_url_params)
        redirect_to root_path, notice: 'Short URL was successfully updated!'
    else
      render :edit, alert: 'Please try again'
    end
  end

  def destroy
    @short_url.destroy if @short_url

    redirect_to root_path, notice: 'Short URL was successfully deleted!'
  end

  def redirect
    @short_url = ShortUrl.find_by(code: params[:code])

    if @short_url.present?
      @short_url.visit_histories.create(ip_address: request.remote_ip)
      @short_url.increment(:click_count)
      @short_url.save

      redirect_to short_url_path(@short_url)
    else
      redirect_to root_path, alert: 'Short URL not found'
    end
  end

  def check_visit_histories
    @short_url = ShortUrl.find(params[:short_url_id])
    @visit_histories = @short_url.visit_histories
  end

  private

  def short_url_params
    params.require(:short_url).permit(:full_url)
  end

  def find_short_url
    @short_url = ShortUrl.find(params[:id])
  end

  def authenticate_admin!
    current_user.admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/short_urls_helper.rb
module ShortUrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniProject20230222</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= notice %>
    <%= alert %>
    <%= yield %>
  </body>
</html>

app/views/short_urls/_form.html.erb
<%= form_for short_url do |short_url| %>
  <%= short_url.label :full_url, 'Full URL: ' %>
  <%= short_url.url_field :full_url %>

  <%= short_url.submit %>
<% end %>

<%= link_to 'Back to Main Page', root_path, class: 'btn btn-primary btn-xs' %>

app/views/short_urls/check_visit_histories.html.erb
<h1>Visit History</h1>

<table class="table">
  <thead>
    <tr>
      <td>IP Address</td>
      <td>Time</td>
    </tr>
  </thead>
  <tbody>
    <% @visit_histories.each do |visit_history| %>
      <tr>
        <td><%= visit_history.ip_address %></td>
        <td><%= visit_history.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back to Main Page', root_path, class: 'btn btn-primary btn-xs' %>

app/views/short_urls/edit.html.erb
<h1>Edit Short URL</h1>

<%= render 'form', short_url: @short_url %>

app/views/short_urls/index.html.erb
<h1>Short URLs</h1>

<% if current_user %>
  <p>
    Hello <%= current_user.email %>
    <br>
    Your role is <span><%= current_user.role %></span>
  </p>  
<% end %>

<%= form_tag '/search', method: 'GET' do %>
  <%= label_tag :code, 'Short URL: ' %>
  <%= text_field_tag :code, params[:code] %>

  <%= submit_tag 'Search' %>
<% end %>

<% if current_user %>
  <div>
      <% if current_user.admin? %>
        <br>
        <h2>Short URL List</h2>
        <%= link_to 'New Short URL', new_short_url_path, class: 'btn btn-success btn-xs' %>
        <table class="table">
          <thead>
            <tr>
              <td>Full URL</td>
              <td>Short URL</td>
              <td>Clicks</td>
              <td></td>
              <td>Actions</td>
            </tr>
          </thead>
          <tbody>
            <% @short_urls.each do |short_url| %>
              <tr>
                <td><%= short_url.full_url %></td>
                <td><%= short_url.code %></td>
                <td><%= short_url.visit_histories.size %></td>
                <td>
                  <%= link_to 'History', visit_histories_path(short_url, short_url_id: short_url.id), class: 'btn btn-info btn-xs' %>
                </td>
                <td>
                  <%= link_to 'Edit', edit_short_url_path(short_url), class: 'btn btn-primary btn-xs' %>
                  <%= link_to 'Delete', short_url_path(short_url), data: {'turbo-method': :delete, turbo_confirm: 'Are you sure?'}, class: 'btn btn-danger btn-xs' %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  <br>
  <%= link_to 'Sign out', destroy_user_session_path, data: {'turbo-method': :delete}, class: 'btn btn-primary btn-xs' %>

<% else %>
  <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary btn-xs' %>
  <br>
  <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-primary btn-xs' %>
<% end %>

app/views/short_urls/new.html.erb
<h1>New Short URL</h1>

<%= render 'form', short_url: @short_url %>

app/views/short_urls/show.html.erb
<h1>Full URL: <%= @short_url.full_url %></h1>

<%= link_to 'Back to Main Page', root_path %>